package com.example.a29th_mar_android_project.util

object AppUtils {
    const val ASIA_BUTTON_IDENTIFIER = 1001
    const val EUROPE_BUTTON_IDENTIFIER = ASIA_BUTTON_IDENTIFIER + 1
    const val NORTH_AMERICA_BUTTON_IDENTIFIER = EUROPE_BUTTON_IDENTIFIER + 1
    const val SOUTH_AMERICA_BUTTON_IDENTIFIER = NORTH_AMERICA_BUTTON_IDENTIFIER + 1
    const val AUSTRALIA_BUTTON_IDENTIFIER = SOUTH_AMERICA_BUTTON_IDENTIFIER + 1
    const val AFRICA_BUTTON_IDENTIFIER = AUSTRALIA_BUTTON_IDENTIFIER + 1

    fun getContinentStringCode(continentId: Int): String = when (continentId) {
        ASIA_BUTTON_IDENTIFIER -> "AS"
        EUROPE_BUTTON_IDENTIFIER -> "EU"
        NORTH_AMERICA_BUTTON_IDENTIFIER -> "NA"
        SOUTH_AMERICA_BUTTON_IDENTIFIER -> "SA"
        AUSTRALIA_BUTTON_IDENTIFIER -> "AU"
        AFRICA_BUTTON_IDENTIFIER -> "AF"
        else -> "UNKNOWN"
    }
}

